version: '3.7'

services:
  angular-app:
    image: nginx
    container_name: ng-abelcastro-dev
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=ng.abelcastro.dev

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - angular-app
    volumes:
      - ./dist:/usr/share/nginx/html
      - /etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email cert@abelcastro.dev --agree-tos --no-eff-email -d ng.abelcastro.dev
